openapi: 3.0.0
info:
  title: "Travel Destination Vaccines REST API"
  description: "An API about vaccines for travel destinations"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /destinations:
    get:
      operationId: "service.TravelDestinationVaccineService.get_destinations"
      tags:
        - "Destinations"
      summary: "Reads the list of travel destinations"
      responses:
        "200":
          description: "Successfully read destinations list"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Destination"
  /destinations/{country}/vaccines:
    get:
      operationId: "service.TravelDestinationVaccineService.get_vaccines"
      tags:
        - "Destinations"
      summary: "Reads the list of vaccines for {country}"
      parameters:
        - $ref: "#/components/parameters/country"
      responses:
        "200":
          description: "Successfully read vaccines list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VaccineList"
        "404":
          description: "Country with the specified name not found"
  /vaccines/{disease}/dosages:
    get:
      operationId: service.VaccineDosageService.get_dosages
      tags:
        - "Vaccines"
      summary: "Reads the list of dosages for {disease}"
      parameters:
        - $ref: "#/components/parameters/disease"
        - $ref: "#/components/parameters/dateOfBirth"
      responses:
        "200":
          description: "Successfully read dosages list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DosageList"
        "404":
          description: "Disease with the specified name not found"

components:
  parameters:
    country:
      name: country
      in: path
      schema:
        type: string
        example: brazil
      required: true
      description: "Name of the country to get"
    disease:
      name: disease
      in: path
      schema:
        type: string
        example: hepatitis-b
      required: true
      description: "Name of the disease to get a vaccine for"
    dateOfBirth:
      name: dateOfBirth
      in: query
      schema:
        type: string
        format: date
        example: 2000-03-31
      description: "Patient's date of birth"
  schemas:
    Vaccine:
      type: object
      properties:
        disease:
          type: string
          description: The name of the disease/illness to get a vaccine for.
          example: Typhoid
        recommendations:
          type: string
          description: Recommendations for the vaccine in the given country provided by the CDC website.
          example: |
            Recommended for most travelers, especially those staying with friends or relatives or visiting smaller cities or rural areas.
    VaccineList:
      type: object
      properties:
        link:
          type: string
          format: uri
          description: A link to the country's CDC travel destination webpage.
          example: https://wwwnc.cdc.gov/travel/destinations/traveler/none/brazil
        items:
          type: array
          items:
            $ref: "#/components/schemas/Vaccine"
    Dosage:
      type: object
      properties:
        brandName:
          type: string
          description: The brand name of the vaccine.
          example: "Avaxim"
        dose:
          type: string
          description: The amount of a medication to take at one specific time.
          example: "1.5 mL"
        form:
          type: string
          enum: [Oral tablet, Injectable, Oral buffer solution]
          description: The form that the medication is taken in.
          example: Injectable
        genericName:
          type: string
          description: The name of the active ingredient.
          example: "Hepatitis A vaccine, inactivated"
        minAge:
          $ref: "#/components/schemas/Age"
          description: The minimum age (years) a person should be for the dosage.
        maxAge:
          $ref: "#/components/schemas/Age"
          description: The maximum age (years) a person should be for the dosage.
        numberOfDoses:
          type: integer
          description: The number of total doses a patient needs to take.
          example: 3
        schedule:
          type: string
          description: The schedule to take the dosage.
          example: "0, 8d+, 15d+"
    DosageList:
      type: object
      properties:
        disease:
          type: string
          description: The name of the disease/illness the dosages are for.
          example: Yellow Fever
        items:
          type: array
          items:
            $ref: "#/components/schemas/Dosage"
    Age:
      type: object
      properties:
        value:
          type: integer
          example: 18
          description: Value of the age.
        unit:
          type: string
          enum: [months, years]
          example: years
          description: Unit of measurement for the age.
    Destination:
      type: object
      properties:
        id:
          type: string
          example: south-korea
          description: Id of the country.
        displayName:
          type: string
          example: South Korea
          description: Country's display name.
